# Generated by Django 4.2.7 on 2026-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
