# Generated by Django 6.0.7 on 2026-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_snapshot',
            field=models.JSONField(default=list),
        ),
    ]
